# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-16 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='cedula',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
